# Generated by Django 4.1.2 on 2022-10-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='https://image.shutterstock.com/image-vector/unknown-package-question-mark-260nw-1212499930.jpg', max_length=1024),
        ),
    ]
